version: '3.8'

services:
  keys:
    container_name: chainflip-keys
    image: chainflip-keys
    volumes:
      - ./config:/chainflip/config

  # geth-rinkeby-light:
  #   container_name: geth-rinkeby-light
  #   image: ethereum/client-go:alltools-stable
  #   restart: always
  #   networks:
  #    - chainflip-net
  #   volumes:
  #     - $PWD/geth-data:/root/.ethereum
  #   command: geth --rinkeby --syncmode "light" --ws --ws.addr "0.0.0.0" --ws.origins "*"

  chainflip-node:
    container_name: chainflip-node
    image: chainflip-node
    restart: always
    networks:
     - chainflip
    ports:
      - 30333:30333
    expose:
      - 9944
      - 9615
    volumes:
      - ./config:/chainflip/config:ro
      - ./chaindata:/chainflip/chaindata
    depends_on:
      - keys

  chainflip-engine:
    container_name: chainflip-engine
    image: chainflip-engine
    restart: always
    networks:
     - chainflip
    volumes:
      - ./config:/chainflip/config:ro
      - ./chaindata:/chainflip/chaindata
    depends_on:
      - keys

networks:
  chainflip:
    name: chainflip-net
