version: '3.8'

services:
  keys:
    container_name: chainflip-keys
    build:
      context: .
      target: keys
      args:
        CHAINFLIP_VERSION: 0.1.0
    volumes:
      - ./config:/chainflip/config

  geth:
    container_name: geth-rinkeby-light
    image: ethereum/client-go:alltools-stable
    restart: always
    networks:
     - chainflip
    volumes:
      - ./geth-data:/root/.ethereum
    command: geth --rinkeby --syncmode "light" --ws --ws.addr "0.0.0.0" --ws.origins "*"

  chainflip-node:
    container_name: chainflip-node
    build:
      context: .
      target: node
      args:
        CHAINFLIP_VERSION: 0.1.0
    restart: always
    networks:
     - chainflip
    ports:
      - 30333:30333
    expose:
      - 9944
      - 9615
    volumes:
      - ./config:/chainflip/config:ro
      - ./chaindata:/chainflip/chaindata
    depends_on:
      - keys
      - geth

  chainflip-engine:
    container_name: chainflip-engine
    build:
      context: .
      target: engine
      args:
        CHAINFLIP_VERSION: 0.1.0
    restart: always
    networks:
     - chainflip
    volumes:
      - ./config:/chainflip/config:ro
      - ./chaindata:/chainflip/chaindata
    depends_on:
      - keys

networks:
  chainflip:
    name: chainflip-net
