version: '3.8'

x-logging:
  &default-logging
  driver: json-file
  options:
    max-size: '20m'
    max-file: '5'

services:
  keys:
    container_name: chainflip-keys
    build:
      context: .
      target: keys
      args:
        CHAINFLIP_VERSION: 0.1.0
    logging: *default-logging
    volumes:
      - ./config:/chainflip/config

  geth:
    container_name: chainflip-geth
    image: ethereum/client-go:alltools-stable
    logging: *default-logging
    restart: always
    networks:
      - chainflip
    ports:
      - 30303:30303
    expose:
      - 8546
    volumes:
      - ./geth-data:/root/.ethereum
    command: geth --rinkeby --syncmode "snap" --ws --ws.addr "0.0.0.0" --ws.origins "*"

  chainflip-node:
    container_name: chainflip-node
    build:
      context: .
      target: node
      args:
        CHAINFLIP_VERSION: 0.1.0
    logging: *default-logging
    restart: always
    networks:
      - chainflip
    ports:
      - 30333:30333
      - 9615:9615
    expose:
      - 9944
    volumes:
      - ./config:/chainflip/config:ro
      - ./chaindata:/chainflip/chaindata
    depends_on:
      - keys
      - geth

  chainflip-engine:
    container_name: chainflip-engine
    build:
      context: .
      target: engine
      args:
        CHAINFLIP_VERSION: 0.1.0
    logging: *default-logging
    restart: always
    networks:
      - chainflip
    volumes:
      - ./config:/chainflip/config:ro
      - ./chaindata:/chainflip/chaindata:ro
    depends_on:
      - keys
      - geth
      - chainflip-node

networks:
  chainflip:
    name: chainflip-net
