version: '3.8'

services:
  keys:
    container_name: chainflip-keys
    image: ghcr.io/cumpsd/chainflip-keys:latest
    volumes:
      - ./config:/chainflip/config

  geth:
    container_name: chainflip-geth
    image: ethereum/client-go:alltools-stable
    restart: always
    networks:
     - chainflip
    ports:
      - 30303:30303
    expose:
      - 8546
    volumes:
      - ./geth-data:/root/.ethereum
    command: geth --rinkeby --syncmode "light" --ws --ws.addr "0.0.0.0" --ws.origins "*"

  chainflip-node:
    container_name: chainflip-node
    image: ghcr.io/cumpsd/chainflip-node:latest
    restart: always
    networks:
     - chainflip
    ports:
      - 30333:30333
      - 9615:9615
    expose:
      - 9944
    volumes:
      - ./config:/chainflip/config:ro
      - ./chaindata:/chainflip/chaindata
    depends_on:
      - keys
      - geth

  chainflip-engine:
    container_name: chainflip-engine
    image: ghcr.io/cumpsd/chainflip-engine:latest
    restart: always
    networks:
     - chainflip
    volumes:
      - ./config:/chainflip/config:ro
      - ./chaindata:/chainflip/chaindata:ro
    depends_on:
      - keys

networks:
  chainflip:
    name: chainflip-net
