{
 "title": "Substrate Metrics",
 "description": "Substrate chain main metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "metric_namespace", "label": "Chain Metrics", "query": "substrate" },
   { "name": "network", "label": "Chain Network", "query": { "query": "label_values(network)" } },
   { "name": "instance", "label": "Chain Instance Host", "query": { "query": "label_values(instance)" } },
   {
    "name": "job",
    "label": "Server Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "node",
    "label": "Server Host",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   },
   { "name": "chain_process", "label": "Chain Process Name", "query": "polkadot" }
  ]
 },
 "panels": [
  { "title": "Chain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Height of the chain",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "[[metric_namespace]]_block_height{instance=\"[[instance]]\",network=\"[[network]]\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Block Finalized",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 11, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "[[metric_namespace]]_block_height{instance=\"[[instance]]\",network=\"[[network]]\",status=~\"finalized|sync_target\"}",
     "legendFormat": "{{instance}} {{status}}"
    }
   ]
  },
  {
   "title": "Networking bytes per second",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate([[metric_namespace]]_sub_libp2p_network_bytes_total{instance=\"[[instance]]\",network=\"[[network]]\"}[5m])",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Block rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate([[metric_namespace]]_block_height{status=\"finalized\",instance=\"[[instance]]\",network=\"[[network]]\"}[10m])*60",
     "legendFormat": "{{instance}}  Blocks / minute"
    }
   ]
  },
  {
   "title": "TXs Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "[[metric_namespace]]_ready_transactions_number{instance=\"[[instance]]\",network=\"[[network]]\"}",
     "legendFormat": "{{instance}}",
     "target": "txcount",
     "type": "timeseries"
    }
   ]
  },
  {
   "title": "Peers count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "[[metric_namespace]]_sub_libp2p_peers_count{instance=\"[[instance]]\",network=\"[[network]]\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "State Cache",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "[[metric_namespace]]_state_cache_bytes{instance=\"[[instance]]\",network=\"[[network]]\"}"
    }
   ]
  },
  {
   "title": "Queued Blocks (sync)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "[[metric_namespace]]_sync_queued_blocks{instance=\"[[instance]]\",network=\"[[network]]\"}"
    }
   ]
  },
  {
   "title": "Relative Block Production Speed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate([[metric_namespace]]_block_height{status=\"finalized\",instance=\"[[instance]]\",network=\"[[network]]\"}[10m])/rate([[metric_namespace]]_block_height{status=\"finalized\",instance=\"[[instance]]\",network=\"[[network]]\"}[1m])",
     "legendFormat": "rate[10m] / rate[1m]"
    }
   ]
  },
  {
   "title": "Blocks Av per min",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase([[metric_namespace]]_block_height{instance=\"[[instance]]\",network=\"[[network]]\",status=~\"finalized|sync_target\"}[1m])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Diff -> ( Best Block - Finalized )",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scalar([[metric_namespace]]_block_height{status=\"best\",instance=\"[[instance]]\",network=\"[[network]]\"})-scalar([[metric_namespace]]_block_height{status=\"finalized\",instance=\"[[instance]]\",network=\"[[network]]\"})",
     "legendFormat": "[[hostname]]"
    }
   ]
  },
  {
   "title": "Running Tasks",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate([[metric_namespace]]_tasks_polling_started_total{instance=\"[[instance]]\",network=\"[[network]]\"}[1m]) - rate([[metric_namespace]]_tasks_polling_duration_count{instance=\"[[instance]]\",network=\"[[network]]\"}[1m])",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "sub_libp2p",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "[[metric_namespace]]_sub_libp2p_connections{instance=\"[[instance]]\",network=\"[[network]]\"}",
     "legendFormat": "{{instance}} connections"
    },
    {
     "expr": "[[metric_namespace]]_sub_libp2p_is_major_syncing{instance=\"[[instance]]\",network=\"[[network]]\"}",
     "legendFormat": "{{instance}} syncing"
    },
    {
     "expr": "[[metric_namespace]]_sub_libp2p_kbuckets_num_nodes{instance=\"[[instance]]\",network=\"[[network]]\"}",
     "legendFormat": "{{instance}} num_nodes"
    }
   ]
  },
  {
   "title": "Sync justifications",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "[[metric_namespace]]_sync_extra_justifications{instance=\"[[instance]]\",network=\"[[network]]\"}",
     "legendFormat": "{{instance}} active"
    },
    {
     "expr": "[[metric_namespace]]_sync_extra_justifications_failed{instance=\"[[instance]]\",network=\"[[network]]\"}",
     "legendFormat": "{{instance}} failed"
    },
    {
     "expr": "[[metric_namespace]]_sync_extra_justifications_importing{instance=\"[[instance]]\",network=\"[[network]]\"}",
     "legendFormat": "{{instance}} importing"
    },
    {
     "expr": "[[metric_namespace]]_sync_extra_justifications_pending{instance=\"[[instance]]\",network=\"[[network]]\"}",
     "legendFormat": "{{instance}} pending"
    }
   ]
  },
  {
   "title": "GRANDPA Validator Messages",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate([[metric_namespace]]_finality_grandpa_communication_gossip_validator_messages{instance=\"[[instance]]\",network=\"[[network]]\"}[5m])",
     "legendFormat": "{{message}}"
    }
   ]
  }
 ]
}