[node_p2p]
node_key_file = "/chainflip/config/node_key"

[state_chain]
ws_endpoint = "ws://chainflip-node:9944"
signing_key_file = "/chainflip/config/signing_key"

[eth]
from_block = 9810000
node_endpoint = "wss://rinkeby.infura.io/ws/v3/7fb203a7ed3d41f4be5ff9309446ea02"
private_key_file = "/chainflip/config/ethereum_key"

[health_check]
hostname = "0.0.0.0"
port = 5555

[signing]
db_file = "data.db"
