global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s

scrape_configs:
- job_name: geth
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /debug/metrics/prometheus
  scheme: http
  static_configs:
  - targets: ['chainflip-geth:30301']

- job_name: chainflip
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets: ['chainflip-node:9615']
