{
 "title": "Chainflip",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "# Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_peers_count{}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Node",
   "type": "logs",
   "gridPos": { "h": 23, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{container_name=\"ghcr.io/cumpsd/chainflip-node:latest\"}"
    }
   ]
  },
  {
   "title": "Engine",
   "type": "logs",
   "gridPos": { "h": 23, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "{container_name=\"ghcr.io/cumpsd/chainflip-engine:latest\"}"
    }
   ]
  }
 ]
}