name: Build

on: [workflow_dispatch]

env:
  DOCKER_REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Parse repository name
        shell: bash
        run: echo REPOSITORY_NAME=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//") >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.12.0
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Inspect builder
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

      - name: Build and push engine
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: false
          target: engine

      - name: Build and push cli
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: false
          target: cli

      - name: Build and push node
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: false
          target: node

      - name: Build and push subkey
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: false
          target: subkey

      - name: Build and push keys
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: false
          target: keys

      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1.1.4
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: v${{ github.run_number }}
      #     release_name: v${{ github.run_number }}
      #     draft: true
      #     prerelease: true
      #     body: |
      #       ${{ github.event.head_commit.message }}
