name: Build

on: [push, workflow_dispatch]

env:
  DOCKER_REGISTRY: ghcr.io
  CHAINFLIP_VERSION: 0.2.6
  SUBKEY_VERSION: 0.1.0

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Parse repository name
        shell: bash
        run: echo REPOSITORY_NAME=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//") >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.3.0

      - name: Inspect builder
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

      - name: Generate engine metadata
        id: meta-engine
        uses: docker/metadata-action@v4.3.0
        with:
          images: |
            ghcr.io/cumpsd/chainflip-engine
          tags: |
            type=sha
            type=raw,value=${{ env.CHAINFLIP_VERSION }}-${{ github.run_number }}
          flavor: |
            latest=true

      - name: Build and push engine
        uses: docker/build-push-action@v3.3.0
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          target: engine
          tags: ${{ steps.meta-engine.outputs.tags }}
          labels: ${{ steps.meta-engine.outputs.labels }}
          build-args: |
            "CHAINFLIP_VERSION=${{ env.CHAINFLIP_VERSION }}"
            "SUBKEY_VERSION=${{ env.SUBKEY_VERSION }}"

      - name: Generate cli metadata
        id: meta-cli
        uses: docker/metadata-action@v4.3.0
        with:
          images: |
            ghcr.io/cumpsd/chainflip-cli
          tags: |
            type=sha
            type=raw,value=${{ env.CHAINFLIP_VERSION }}-${{ github.run_number }}
          flavor: |
            latest=true

      - name: Build and push cli
        uses: docker/build-push-action@v3.3.0
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          target: cli
          tags: ${{ steps.meta-cli.outputs.tags }}
          labels: ${{ steps.meta-cli.outputs.labels }}
          build-args: |
            "CHAINFLIP_VERSION=${{ env.CHAINFLIP_VERSION }}"
            "SUBKEY_VERSION=${{ env.SUBKEY_VERSION }}"

      - name: Generate node metadata
        id: meta-node
        uses: docker/metadata-action@v4.3.0
        with:
          images: |
            ghcr.io/cumpsd/chainflip-node
          tags: |
            type=sha
            type=raw,value=${{ env.CHAINFLIP_VERSION }}-${{ github.run_number }}
          flavor: |
            latest=true

      - name: Build and push node
        uses: docker/build-push-action@v3.3.0
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          target: node
          tags: ${{ steps.meta-node.outputs.tags }}
          labels: ${{ steps.meta-node.outputs.labels }}
          build-args: |
            "CHAINFLIP_VERSION=${{ env.CHAINFLIP_VERSION }}"
            "SUBKEY_VERSION=${{ env.SUBKEY_VERSION }}"

      - name: Generate subkey metadata
        id: meta-subkey
        uses: docker/metadata-action@v4.3.0
        with:
          images: |
            ghcr.io/cumpsd/chainflip-subkey
          tags: |
            type=sha
            type=raw,value=${{ env.CHAINFLIP_VERSION }}-${{ github.run_number }}
          flavor: |
            latest=true

      - name: Build and push subkey
        uses: docker/build-push-action@v3.3.0
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          target: subkey
          tags: ${{ steps.meta-subkey.outputs.tags }}
          labels: ${{ steps.meta-subkey.outputs.labels }}
          build-args: |
            "CHAINFLIP_VERSION=${{ env.CHAINFLIP_VERSION }}"
            "SUBKEY_VERSION=${{ env.SUBKEY_VERSION }}"

      - name: Generate keys metadata
        id: meta-keys
        uses: docker/metadata-action@v4.3.0
        with:
          images: |
            ghcr.io/cumpsd/chainflip-keys
          tags: |
            type=sha
            type=raw,value=${{ env.CHAINFLIP_VERSION }}-${{ github.run_number }}
          flavor: |
            latest=true

      - name: Build and push keys
        uses: docker/build-push-action@v3.3.0
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          target: keys
          tags: ${{ steps.meta-keys.outputs.tags }}
          labels: ${{ steps.meta-keys.outputs.labels }}
          build-args: |
            "CHAINFLIP_VERSION=${{ env.CHAINFLIP_VERSION }}"
            "SUBKEY_VERSION=${{ env.SUBKEY_VERSION }}"

      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1.1.4
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: v${{ github.run_number }}
      #     release_name: v${{ github.run_number }}
      #     draft: true
      #     prerelease: true
      #     body: |
      #       ${{ github.event.head_commit.message }}
